import { Genre } from "../enums/index.ts";

export const genreIndexes = new Map<string, number>([
  [Genre.ACTION, 2],
  [Genre.ADULT, 3],
  [Genre.ADVENTURE, 4],
  [Genre.COMEDY, 6],
  [Genre.COOKING, 7],
  [Genre.DOUJINSHI, 9],
  [Genre.DRAMA, 10],
  [Genre.ECCHI, 11],
  [Genre.FANTASY, 12],
  [Genre.GENDERBENDER, 13],
  [Genre.HAREM, 14],
  [Genre.HISTORICAL, 15],
  [Genre.HORROR, 16],
  [Genre.ISEKAI, 45],
  [Genre.JOSEI, 17],
  [Genre.MANHUA, 44],
  [Genre.MANHWA, 43],
  [Genre.MARTIALARTS, 19],
  [Genre.MATURE, 20],
  [Genre.MECHA, 21],
  [Genre.MEDICAL, 22],
  [Genre.MYSTERY, 24],
  [Genre.ONESHOT, 25],
  [Genre.PSYCHOLOGICAL, 26],
  [Genre.ROMANCE, 27],
  [Genre.SCHOOLLIFE, 28],
  [Genre.SCIFI, 29],
  [Genre.SEINEN, 30],
  [Genre.SHOUJO, 31],
  [Genre.SHOUJOAI, 32],
  [Genre.SHOUNEN, 33],
  [Genre.SHOUNENAI, 34],
  [Genre.SLICEOFLIFE, 35],
  [Genre.SMUT, 36],
  [Genre.SPORTS, 37],
  [Genre.SUPERNATURAL, 38],
  [Genre.TRAGEDY, 39],
  [Genre.WEBTOONS, 40],
  [Genre.YAOI, 41],
  [Genre.YURI, 42],
]);

export const getGenreURL = (genre: Genre) =>
  `https://manganelo.com/genre-${genreIndexes.get(genre)}`;
