name: Tests
on: [push]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish to Registry
        uses: elgohr/Publish-Docker-Github-Action@master
        with:
          name: antoniogamiz/manga-api
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
  run-tests:
    runs-on: ubuntu-latest
    container: antoniogamiz/manga-api
    steps:
      - name: Checkout module
        uses: actions/checkout@v2
      - name: Linting
        run: vr lint
      - name: Test Deno Module
        run: vr test
