name: Tests

on: [push]

jobs:
  shouldBuild:
    runs-on: ubuntu-latest
    outputs:
      changed: ${{ steps.shouldBuild.outputs.files }}
    steps:
      - uses: actions/checkout@v2
      - uses: dorny/paths-filter@v2
        id: shouldBuild
        with:
          filters: |
            files:
              - 'Dockerfile'
              - 'src/deps.ts'
              - 'scripts.yaml'
              - 'tsconfig.json'
              - '.github/workflows/ci.yml'
  build:
    needs: shouldBuild
    runs-on: ubuntu-latest
    if: ${{ needs.shouldBuild.outputs.changed == 'true' }}
    steps:
      - uses: actions/checkout@v2
      - name: Publish to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GH_REGISTRY_TOKEN }}
      - name: Push
        run: docker build -t ghcr.io/antoniogamiz/manga-api . && docker push ghcr.io/antoniogamiz/manga-api
  run-tests:
    needs: [build, shouldBuild]
    if: always()
    runs-on: ubuntu-latest
    steps:
      - name: Checkout module
        uses: actions/checkout@v2
      - name: Run tests
        run: docker run -t -v `pwd`:/test ghcr.io/antoniogamiz/manga-api
